### ISSUE TITLE
Any introduction about `git.kaiostech.com` ?

### ISSUE THREAD

**Issue by viko16** [zwts/react-notes#1]
Hello @zwts , seems some dependencies are from `git.kaiostech.com`, but i can't find any useful information about that from Google.
Is there any introduction or document you can share.

Thanks a lot.

**Comment by karuncodes** [comment]
KaiOS is a fork of Mozilla OS and all the OS related documentation is available on Mozilla Developer Network. 

Building an app on KaiOS: 
https://developer.mozilla.org/en-US/docs/Archive/B2G_OS/Firefox_OS_apps/Building_apps_for_Firefox_OS


OS info: 
https://wiki.mozilla.org/B2G
